/* eslint-disable */
/* global WebImporter */
/**
 * Parser for accordion-faq. Base: accordion.
 * Source: https://wknd-trendsetters.site/ (FAQ)
 * Generated: 2026-09-02
 *
 * Source structure: a faq-list of <details class="faq-item"> elements, each with a
 * <summary> question (a text span plus a decorative +/- SVG icon) and a
 * <div class="faq-answer"> body.
 * Output (accordion convention): 2 columns, one row per item —
 *   cell 1 = question label (text only; the +/- toggle icon is regenerated by the decorator)
 *   cell 2 = answer body content.
 */
export default function parse(element, { document }) {
  const items = Array.from(element.querySelectorAll('details.faq-item, details'));

  const cells = [];
  items.forEach((item) => {
    const summary = item.querySelector('summary');
    // Prefer the text span for the question; fall back to summary text.
    const questionSpan = summary ? summary.querySelector('span') : null;
    const question = questionSpan
      ? questionSpan.textContent.trim()
      : (summary ? summary.textContent.trim() : '');

    // Answer body: everything inside the answer wrapper.
    const answer = item.querySelector('.faq-answer') || item.querySelector('div:not(summary)');
    const answerCell = answer || '';

    if (!question && !answer) return;
    cells.push([question, answerCell]);
  });

  // Empty-block guard.
  if (!cells.length) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'accordion-faq', cells });
  element.replaceWith(block);
}
